CREATE TABLE owners (
  id INTEGER PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
);

CREATE TABLE cars (
  id INTEGER PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  brand VARCHAR(255) NOT NULL,
  owner_id INTEGER NOT NULL UNIQUE,
  FOREIGN KEY(owner_id) REFERENCES owners(id)
);

CREATE TABLE parts (
  id INTEGER PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  car_id INTEGER NOT NULL UNIQUE,
  FOREIGN_KEY car_id REFERENCES cars(id)
);
